-- Database: hotel-reservation-db

-- DROP DATABASE "hotel-reservation-db";

CREATE DATABASE "hotel-teste-db"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- public.address definition

-- Drop table

-- DROP TABLE public.address;

CREATE TABLE public.address (
	id_address int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	city varchar(255) NULL,
	country varchar(255) NULL,
	description varchar(255) NULL,
	neighborhood varchar(255) NULL,
	"number" int4 NULL,
	state varchar(255) NULL,
	street varchar(255) NULL,
	CONSTRAINT address_pkey PRIMARY KEY (id_address)
);

-- public.rate definition

-- Drop table

-- DROP TABLE public.rate;

CREATE TABLE public.rate (
	id_rate int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
	price_type varchar(255) NULL,
	CONSTRAINT rate_pkey PRIMARY KEY (id_rate)
);

-- public.hotel definition

-- Drop table

-- DROP TABLE public.hotel;

CREATE TABLE public.hotel (
	id_hotel int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	classification int4 NULL,
	cnpj varchar(255) NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	phone_number varchar(255) NULL,
	id_address int8 NULL,
	CONSTRAINT hotel_pkey PRIMARY KEY (id_hotel),
	CONSTRAINT uk_1u2pywhfbc294l9udblotbmep UNIQUE (cnpj)
);


-- public.hotel foreign keys
ALTER TABLE public.hotel ADD CONSTRAINT fkp3l08bu8uotbnym8g10s376v4 FOREIGN KEY (id_address) REFERENCES public.address(id_address);

-- public.customer definition

-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE public.customer (
	id_hotel int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cpf varchar(255) NULL,
	email varchar(255) NULL,
	loyalty int4 NULL,
	"name" varchar(255) NULL,
	phone_number varchar(255) NULL,
	id_address int8 NULL,
	CONSTRAINT customer_pkey PRIMARY KEY (id_hotel),
	CONSTRAINT uk_cwtgtb16nebxu54elskdjei66 UNIQUE (cpf),
	CONSTRAINT uk_dwk6cx0afu8bs9o4t536v1j5v UNIQUE (email)
);


-- public.customer foreign keys

ALTER TABLE public.customer ADD CONSTRAINT fkrtg0ytybwvot9ne0txhl5jxy4 FOREIGN KEY (id_address) REFERENCES public.address(id_address);

-- public.booking definition

-- Drop table

-- DROP TABLE public.booking;

CREATE TABLE public.booking (
	id_booking int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	checkin date NULL,
	checkout date NULL,
	booking_remarks varchar(255) NULL,
	booking_type int4 NULL,
	id_customer int8 NULL,
	id_hotel int8 NULL,
	booking_number int8 NULL,
	booking_date timestamp NULL,
	booking_price float8 NULL,
	active bool NULL,
	CONSTRAINT booking_pkey PRIMARY KEY (id_booking),
	CONSTRAINT uk_6j74n7w8mp19sixr5272028mk UNIQUE (booking_number)
);


-- public.booking foreign keys
ALTER TABLE public.booking ADD CONSTRAINT fkpik2mrag1cnn0tqf6pem6iuyc FOREIGN KEY (id_hotel) REFERENCES public.hotel(id_hotel);
ALTER TABLE public.booking ADD CONSTRAINT fksfkmk4sahyegxnjceqmpuy407 FOREIGN KEY (id_customer) REFERENCES public.customer(id_hotel);

-- public.hotel_table_rate definition

-- Drop table

-- DROP TABLE public.hotel_table_rate;

CREATE TABLE public.hotel_table_rate (
	id_hotel int8 NOT NULL,
	id_rate int8 NOT NULL,
	CONSTRAINT hotel_table_rate_pkey PRIMARY KEY (id_hotel, id_rate),
	CONSTRAINT uk_ri8ovycgbj1r572vetl7h60tj UNIQUE (id_rate)
);


-- public.hotel_table_rate foreign keys
ALTER TABLE public.hotel_table_rate ADD CONSTRAINT fkf4l9y0rkt8mor9d016q5qq0s2 FOREIGN KEY (id_hotel) REFERENCES public.hotel(id_hotel);
ALTER TABLE public.hotel_table_rate ADD CONSTRAINT fkmocidry2b63sxcm5p88yg3lp4 FOREIGN KEY (id_rate) REFERENCES public.rate(id_rate);